# Generated by Django 4.2.4 on 2023-08-15 12:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="room",
            options={"ordering": ["-created", "-update"]},
        ),
        migrations.AlterField(
            model_name="room",
            name="created",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="room",
            name="update",
            field=models.DateTimeField(auto_created=True),
        ),
    ]
