# Generated by Django 4.2.4 on 2023-08-17 13:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("home", "0002_alter_room_options_alter_room_created_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="participents",
            field=models.ManyToManyField(
                blank=True, related_name="participents", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
